"""
Domain model representing an order generated by a strategy.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

from models.enums import OrderAction
from models.instrument import Instrument


@dataclass(frozen=True, slots=True)
class Order:
    """
    Represents a single buy or sell instruction.
    """

    timestamp: datetime
    action: OrderAction
    instrument: Instrument
    quantity: int
    price: float