"""
Domain models representing trading signals generated by a strategy.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional

from models.enums import Underlying


class SignalType(str, Enum):
    """Types of trading signals a strategy can generate."""
    
    BUY_PAIR = "BUY_PAIR"
    EXIT_PAIR = "EXIT_PAIR"
    EXIT_ALL = "EXIT_ALL"


@dataclass(frozen=True, slots=True)
class TradingSignal:
    """
    Represents the intent of a strategy.
    
    The ExecutionEngine receives this signal and converts it into
    concrete Orders based on the current market snapshot.
    """
    
    signal_type: SignalType
    underlying: Underlying
    strike: Optional[int] = None
